name : CI/CD for Flask App

# Trigger the workflow on any push or pull to / from master
on : 
    push:
        branches:
            - master
    pull_request:
        branches:
            -master

jobs :  #workflow
    build-and-test:   #CI job name
        runs-on: ubuntu-latest  # which container the job needs to run

        steps:  # workflow steps
        - name : checkout the code  # clone / check out the code from repo
          uses : actions/checkout@v3    # using pre-built actions

        - name : Python environmnet # create python environment 
          uses : actions/setup-python@v4    # using pre-built actions
          with :
                python-version : '3.10'

        - name : Install requirements   # install dependencies
          run : |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name : Run unit test
          run : pytest

    build-and-publish:   # CD job name
        runs-on : ubuntu-latest # which container the job needs to run

        steps:  # workflow steps
            - name: checkout code
              uses : actions/checkout@v3

            - name : Setup docker buildx    # pre-built github action for building docker image using docker file
              uses : docker/setup-buildx-action@v2

            - name : Login to docker hub
              uses : docker/login-action@v2 # login to dockerhub using pre-built action
              with :
                username : ${{secrets.DOCKER_USER_NAME}}
                password : ${{secrets.DOCKER_PASSWORD}}

            - name : Build and push docker image
              uses : docker/build-push-action@v4
              with :
                context : Demo_2
                push : true
                tags : ${{secrets.DOCKER_USER_NAME}}/flasktest-app:latest

            - name : Image digest   # display  specific version of docker image
              run : echo ${{steps.build-and-publish.outputs.digest}}